language: erlang
otp_release:
  - 21.0
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
script:
  - ./rebar3 version
  - DEBUG=1 ./rebar3 as test do dialyzer, xref, coveralls
  - ls _build/test/cover/
  - ./rebar3 as test do coveralls send
notifications:
  email:
    recipients:
      - mikeyhc@atmosia.net
